---
title: "Importing Data Subset"
author: "Hugo van den Belt"
date: "2025-02-19"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

# Importing Data Subset

## Load Libraries
```{r}
library(haven)
library(dplyr)
```


## File path
```{r}
file_path <- "/Users/hugovandenbelt/Downloads/GSS_stata/gss7222_r4.dta"
gss_data <- read_dta(file_path)
```

The original Data Set can be downloaded from [the GSS website] (https://gss.norc.org/us/en/gss/get-the-data/stata.html) by downloading "Cumulative Data Set (cross-sectional samples from all years)"

## Select relevant variables
```{r}
subset_data <- gss_data %>%
  select(year, id, marital, sibs, childs, age, educ, degree, padeg, 
         madeg, sex, race, reg16, income, rincome, region, partyid, polviews, 
         relig, happy, class, satfin, finalter, finrela)

subset_data <- subset_data %>%
  mutate(across(where(is.labelled), as.numeric))

# Convert necessary variables to factors
# It would be easier to subset directly as factors, but that messes up the NA observations, hence this workaround
factor_vars <- c("year", "marital", "educ", "degree", 
                 "padeg", "madeg", "sex", "race", "reg16", "income", "rincome", "region", 
                 "partyid", "polviews", "relig", "happy", "class", 
                 "satfin", "finalter", "finrela")

subset_data <- subset_data %>%
  mutate(across(all_of(factor_vars), as.factor))

write.csv(subset_data, "/Users/hugovandenbelt/Documents/GitHub/Research Note EUR Recent Advancements/GSS_subset.csv", row.names = FALSE)

head(subset_data)
```

## Check how many NAs exist in each column
```{r}
colSums(is.na(subset_data))
```


